Fixing format error when running tutorial_6
I was getting the following error when running tutorial_6.py:

Traceback (most recent call last):
  File ".\tutorial_6.py", line 311, in <module>
    cumulative_reward = agent.run(agent_host)
  File ".\tutorial_6.py", line 162, in run
    total_reward += self.act(world_state, agent_host, current_r)
  File ".\tutorial_6.py", line 107, in act
    self.drawQ( curr_x = int(obs[u'XPos']), curr_y = int(obs[u'ZPos']) )
  File ".\tutorial_6.py", line 230, in drawQ
    color_string = '#%02x%02x%02x' % (255-color, color, 0)
TypeError: %x format: an integer is required, not float

Using the "int" function in line 229 solved the problem for me.
I hope this helps.